### PR TITLE
Many Improvements: lxml, whitelist-parameter, itemlist support, ... 

### PR DESCRIPTION
**Pull request by TorHou**

### CODE REVIEW

**Comment by bgruening** [comment]
Hi can we merge this. This is used to generate the newest version of OpenMS Galaxy wrappers.

**Comment by TorHou** [comment]
@bgruening I worked in you comments. FileMerge should now work as intended and all filetypes should be lowercase.

**Comment by bgruening** [comment]
Nice, thanks!

**Comment by chahuistle** [comment]
I will merge this as soon as I have a chance... I was on vacation and I've
been out sick this week...

Cheers,
Luis

On Fri, Jan 16, 2015 at 10:54 AM, Björn Grüning <notifications@github.com>
wrote:

> Nice, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/genericworkflownodes/GalaxyConfigGenerator/pull/2#issuecomment-70231170>
> .
>



-- 
Luis Javier de la Garza Treviño

**Pull request merged**
